(function(n){var m=window.AmazonUIPageJS||window.P,t=m._namespace||m.attributeErrors,g=t?t("TwisterHardlinesDetailPageAsset"):m;g.guardFatal?g.guardFatal(n)(g,window):g.execute(function(){n(g,window)})})(function(n,m,t){n.when("A","jQuery","atf").execute(function(g,a){g.on.ready(function(){function c(b,c,d,e,f){a(b).slideToggle(300);a(c).slideToggle(300);a(d).toggleClass("tmmShowPrompt tmmHidePrompt");a(e).toggleClass("tmmShowPrompt tmmHidePrompt");a(f).toggleClass("rotate")}function d(b){b.position();
b.width();a(".swatchElement");b.find(".swatchElement").each(function(){a(this).attr("data-width",a(this).width())});a("#formats").find(".a-row").removeClass("nonJSFormats")}function b(){var b=a("#formats"),c=b.width()-40,d=0;b.find(".swatchElement").each(function(){a(this).is(":visible")&&(d+=a(this).width())});d>c?a(b.find(".swatchElement:visible").get().reverse()).each(function(){var b=0,e=!1;a(this).find(".format").hasClass("a-button-selected")?(b=a(this).prev(".swatchElement").width(),e=a(this).prev(".swatchElement").is(":hidden"),
a(this).prev(".swatchElement").hide()):(b=a(this).width(),e=a(this).is(":hidden"),a(this).hide());e||(d-=b);return d>c}):d<c&&b.find(".swatchElement").each(function(){if(a(this).is(":hidden"))return a(this).attr("data-width")<=c-d&&a(this).show(),!1})}var f=0,e=0,l,h=function(a){"undefined"!=typeof a&&(l=new a.ImpressionLogger("dpbxapps","bxapps-atfMarker",!0,!0))};"undefined"!=typeof amznJQ?amznJQ.available("DPClientLogger",function(){h(m.DPClientLogger)}):n.when("DPClientLogger").execute(h);g.declarative("tmm-see-more-editions-click",
["click"],function(b){var d=b.data,e=d.metabindingUrl;if(b.$target.hasClass("a-link-expander")||b.$target.parent().hasClass("a-link-expander")){var d=d.metabindingPlaceHolder,f="#metabinding_row_top_"+d,h="#metabinding_row_bottom_"+d,k="#editionsSeePrompt_"+d,l="#editionsHidePrompt_"+d,n="#editionsIcon_"+d,p="isAjaxComplete_"+d,t="isAjaxInProgress_"+d;b="#tmmSpinnerDiv_"+d;var G=g.state("mediamatrix-state"),d=G["url_"+d].replace(/&amp;/g,"&");a("#formats .tmmErrorClass").hide();"1"===G[p]||"1"===
G[t]?c(f,h,k,l,n):(g.ajax(d,{method:"get",success:function(){G[p]="1";g.state("mediamatrix-state",G);c(f,h,k,l,n)},indicator:a(b),error:function(){a($tmmErrorDiv).show();G[t]="0";g.state("mediamatrix-state",G)}}),G[t]="1",g.state("mediamatrix-state",G))}else"#"!==e&&(m.location=e)});if(0<a("#formats > .a-link-expander").length){var k=m.ue;k&&k.count&&k.count("mediaMatrixExpanderPresent",1)}a("#formats > .a-link-expander").click(function(){c("#tmmSwatches","#twister","#showMoreFormatsPrompt","#hideMoreFormatsPrompt",
"#formatsIcon");if(!e){var b=m.ue;b&&b.count&&b.count("mediaMatrixExpanderClicked",1);e=1}l&&a("#twister").is(":visible")&&!f&&(l.logImpression("tmm-show-more-formats-viewed"),f=1)});var k=g.state("mediamatrix-state"),p="1";"undefined"!==typeof k&&"undefined"!==typeof k.showHybridMediaMatrix&&"1"===k.showHybridMediaMatrix?p="0":"undefined"!==typeof k&&"undefined"!==typeof k.isDvdWeblabEnabled&&"1"===k.isDvdWeblabEnabled&&(p="0");"1"===p&&(a("#formats.responsive").each(function(){d(a(this))}),b(),
g.on("resize",b));a("#formats .unselected .format").mouseenter(function(){a(this).find(".a-color-secondary").addClass("a-color-price").removeClass("a-color-secondary")}).mouseleave(function(){a(this).find(".a-color-price").addClass("a-color-secondary").removeClass("a-color-price")});a("#landingItemRentalLink").attr("href","javascript:document.getElementById('rentBuySection').click();")})});n.when("A","jQuery","a-dropdown").execute(function(g,a,c){function d(a){return a?a.replace(/&#0/g,"&#"):undef}
function b(a){for(var b=a.getOptions(),b=b?b.size():0,c=1;c<b;c++)a.removeOption(1)}function f(b,c){var e=b.getOption(0),f=e.info()[0];e.remove();a.each(c,function(a,c){b.addOption({text:Q[d(c)],value:c,css_class:"dropdownAvailable"},1)});b.addOption(f,0);b.val(f.value)}function e(a){v=a.value;b(A);"-1"!==v&&(l(),f(A,Object.keys(n[d(v)])))}function l(){Object.keys||(Object.keys=function(){var a=Object.prototype.hasOwnProperty,b=!{toString:null}.propertyIsEnumerable("toString"),c="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),
d=c.length;return function(e){if("object"!==typeof e&&("function"!==typeof e||null===e))throw new TypeError("Object.keys called on non-object");var f=[],g;for(g in e)a.call(e,g)&&f.push(g);if(b)for(g=0;g<d;g++)a.call(e,c[g])&&f.push(c[g]);return f}}())}function h(a){E=a.value;"-1"!==E&&"-1"!==v&&(m.location=t[n[d(v)][d(E)]])}function k(a){a=a.value;"-1"!==a&&(m.location=t[d(a)])}var n,q=g.state("dcdMetaData");if(q){var t=q.asinToDetailPageURLMap,Q=q.truncatedValuesMap,x=q.dimensionKeys,D=x[0],v=-1,
E=-1,A;2===x.length?(n=q.doubleValuesToAsinMap,q=x[1],x=c.getSelect("native_dcd_dropdown_"+D),A=c.getSelect("native_dcd_dropdown_"+q),x.setValue("-1"),A.setValue("-1"),b(A),g.on("a:dropdown:selected:"+D,e),g.on("a:dropdown:selected:"+q,h)):(x=c.getSelect("native_dcd_dropdown_"+D),(c=q.selectedAsin)?x.setValue(c):x.setValue("-1"),g.on("a:dropdown:selected:asin-redirect",k))}})});
/* ******** */
(function(n){var m=window.AmazonUIPageJS||window.P,t=m._namespace||m.attributeErrors,g=t?t("PInfoHardlinesDetailPageAsset"):m;g.guardFatal?g.guardFatal(n)(g,window):g.execute(function(){n(g,window)})})(function(n,m,t){n.when("A","jQuery","atf").execute(function(g,a,c){function d(){var b=parseInt(a("#byline").width()),c=0;a("#byline .author").each(function(){a(this).is(".notFaded")&&(c+=a(this).outerWidth())});c+=a("#byline .more").outerWidth();if(c>b){var d=a("#byline .author.notFaded").length;a(a("#byline .author.notFaded").get().reverse()).each(function(g){c>
b&&g<d-1&&(g=a(this).width(),a(this).removeClass("notFaded"),a(this).fadeOut(10,function(){a(this).hide()}),c-=g,a("#byline .moreCount").html(a("#byline .author").length-a("#byline .author.notFaded").length),a("#byline .more").addClass("notFaded").fadeIn(10))})}else if(c<b&&a("#byline .author.notFaded").length<a("#byline .author").length){var g=b-c;a("#byline .author").each(function(){if(!a(this).hasClass("notFaded")){var b=a(this).outerWidth();b<=g?(g-=b,a(this).addClass("notFaded").fadeIn(10),b=
a("#byline .author").length-a("#byline .author.notFaded").length,0===b?a("#byline .more").removeClass("notFaded").fadeOut(10):(a("#byline .moreCount").html(b),a("#byline .more").addClass("notFaded").fadeIn(10))):g=0}})}}a("#byline .showMoreLink").click(function(){a("#byline .author").each(function(){a(this).hasClass("notFaded")||a(this).addClass("notFaded").fadeIn(0);a("#byline .more").removeClass("notFaded").fadeOut(0)});return!1});a("#byline .contributorNameID").mouseenter(function(){var b=a(this).attr("data-asin"),
c={},d="isAjaxComplete_"+b,l="isAjaxInProgress_"+b,h=g.state("popoverImage-state");c.entityID=b;"1"!==h[d]&&"1"!==h[l]&&(a.ajax({url:"/gp/product/utility/by-line/book-contributor-details/ajax/author-image.html",data:c,dataType:"html",timeout:1E3,success:function(c){a("#contributorImageContainer"+b).get(0).innerHTML=c;h[d]="1";g.state("popoverImage-state",h)},error:function(){h[l]="0";g.state("popoverImage-state",h)}}),h[l]="1",g.state("popoverImage-state",h))});(function(b){var c=parseInt(b.width()),
d=parseInt(b.find(".more").outerWidth()),g=0;a("#byline .author").each(function(){a(this).is(".notFaded")&&(g+=a(this).outerWidth())});a("#byline .more").attr("data-width",d);var h=c-d;if(h>g)b.find(".author").each(function(){var b=a(this).index();3<=parseInt(b)?(b=a(this).outerWidth(),a(this).attr("data-width",b),b<h?(h-=b,a(this).addClass("notFaded"),a(this).fadeIn("slow")):(h=0,a(this).fadeOut("slow"))):(b=a(this).outerWidth(),a(this).attr("data-width",b),h-=b)});else{var k=a("#byline .author.notFaded").length;
a(a("#byline .author.notFaded").get().reverse()).each(function(b){h<g&&b<k-1&&(b=a(this).outerWidth(),g-=b,a(this).fadeOut("slow").removeClass("notFaded"))})}c=b.find(".author").length-b.find(".author.notFaded").length;0<c&&(b.find(".moreCount").html(c),b.find(".more").fadeIn("slow"),b.find(".more").addClass("notFaded"))})(g.$("#byline"));a(m).resize(function(){d()})});n.when("A","jQuery","atf").execute(function(g,a,c){function d(){var b=parseInt(a("#bylineInfo").width()),c=0;a("#bylineInfo .author").each(function(){a(this).is(".notFaded")&&
(c+=a(this).outerWidth())});c+=a("#bylineInfo .more").outerWidth();if(c>b){var d=a("#bylineInfo .author.notFaded").length;a(a("#bylineInfo .author.notFaded").get().reverse()).each(function(g){c>b&&g<d-1&&(g=a(this).width(),a(this).removeClass("notFaded"),a(this).fadeOut(10,function(){a(this).hide()}),c-=g,a("#bylineInfo .moreCount").html(a("#bylineInfo .author").length-a("#bylineInfo .author.notFaded").length),a("#bylineInfo .more").addClass("notFaded").fadeIn(10))})}else if(c<b&&a("#bylineInfo .author.notFaded").length<
a("#bylineInfo .author").length){var g=b-c;a("#bylineInfo .author").each(function(){if(!a(this).hasClass("notFaded")){var b=a(this).outerWidth();b<=g?(g-=b,a(this).addClass("notFaded").fadeIn(10),b=a("#bylineInfo .author").length-a("#bylineInfo .author.notFaded").length,0===b?a("#bylineInfo .more").removeClass("notFaded").fadeOut(10):(a("#bylineInfo .moreCount").html(b),a("#bylineInfo .more").addClass("notFaded").fadeIn(10))):g=0}})}}a("#bylineInfo .showMoreLink").click(function(){a("#bylineInfo .author").each(function(){a(this).hasClass("notFaded")||
a(this).addClass("notFaded").fadeIn(0);a("#bylineInfo .more").removeClass("notFaded").fadeOut(0)});return!1});a("#bylineInfo .contributorNameID").mouseenter(function(){var b=a(this).attr("data-asin"),c={},d="isAjaxComplete_"+b,l="isAjaxInProgress_"+b,h=g.state("popoverImage-state");c.entityID=b;"1"!==h[d]&&"1"!==h[l]&&(a.ajax({url:"/gp/product/utility/by-line/book-contributor-details/ajax/author-image.html",data:c,dataType:"html",timeout:1E3,success:function(c){a("#contributorImageContainer"+b).get(0).innerHTML=
c;h[d]="1";g.state("popoverImage-state",h)},error:function(){h[l]="0";g.state("popoverImage-state",h)}}),h[l]="1",g.state("popoverImage-state",h))});(function(b){var c=parseInt(b.width()),d=parseInt(b.find(".more").outerWidth()),g=0;a("#bylineInfo .author").each(function(){a(this).is(".notFaded")&&(g+=a(this).outerWidth())});a("#bylineInfo .more").attr("data-width",d);var h=c-d;if(h>g)b.find(".author").each(function(){var b=a(this).index();3<=parseInt(b)?(b=a(this).outerWidth(),a(this).attr("data-width",
b),b<h?(h-=b,a(this).addClass("notFaded"),a(this).fadeIn("slow")):(h=0,a(this).fadeOut("slow"))):(b=a(this).outerWidth(),a(this).attr("data-width",b),h-=b)});else{var k=a("#bylineInfo .author.notFaded").length;a(a("#bylineInfo .author.notFaded").get().reverse()).each(function(b){h<g&&b<k-1&&(b=a(this).outerWidth(),g-=b,a(this).fadeOut("slow").removeClass("notFaded"))})}c=b.find(".author").length-b.find(".author.notFaded").length;0<c&&(b.find(".moreCount").html(c),b.find(".more").fadeIn("slow"),b.find(".more").addClass("notFaded"))})(g.$("#bylineInfo"));
a(m).resize(function(){d()})});n.when("A","jQuery").register("product-description-fix",function(g,a){return{fixTableIssue:function(){a("#productDescription .productDescriptionWrapper table").each(function(){var c=a(this).attr("width");"undefined"!==typeof c?a(this).css("width",c):a(this).css("width","auto")})}}})});
/* ******** */
(function(n){var m=window.AmazonUIPageJS||window.P,t=m._namespace||m.attributeErrors,g=t?t("OffersHardlinesDetailPageAsset"):m;g.guardFatal?g.guardFatal(n)(g,window):g.execute(function(){n(g,window)})})(function(n,m,t){n.when("A","jQuery","atf").register("accordionBuyBoxJS",function(g,a,c){var d={updateCssClass:function(b){var c=a("#rbbContainer");c.find(".selected .a-icon-radio-active").removeClass("a-icon-radio-active").addClass("a-icon-radio-inactive");c.find(".selected .offer-price").removeClass("a-color-price").addClass("a-color-secondary");
b.parents(".rbbSection").removeClass("unselected").addClass("selected");b.parents(".rbbSection").toggleClass("dp-accordion-active",500);b.find(".a-icon-radio-inactive").removeClass("a-icon-radio-inactive").addClass("a-icon-radio-active");b.find(".offer-price").removeClass("a-color-secondary").addClass("a-color-price");a("#rbbContainer .rbbSection .rbbContent").find(".offer-price").removeClass("a-color-secondary").addClass("a-color-price")},animate:function(b){var c=a("#rbbContainer"),d=b.attr("id"),
g,h;c.find(".rbbSection").each(function(b,c){a(c).find(".rbbHeader")[0].id==d?g=a(c):a(c).hasClass("selected")&&(h=a(c))});h.find(".rbbContent").slideUp(500,function(){h.removeClass("selected").addClass("unselected");h.toggleClass("dp-accordion-active",500)});g.find(".rbbContent").slideDown(500);a.browser.msie&&7==parseInt(a.browser.version,10)&&(g.find(".rbbContent").css("display","inline"),setTimeout(function(){g.find(".rbbContent").css("display","block")},505))},oneClickJS:function(){a("#one-click-button, #one-click-button-ubb").click(function(){var b=
"https://"+m.location.host+a("#addToCart").attr("action");a("#addToCart").attr("action",b);return!0})},usedBuyBoxJS:function(){a("#one-click-button-ubb, #usedbuyBox #add-to-cart-button-ubb").click(function(){var b=a("#addToCart"),c=b.attr("action").replace("ref=dp_start-bbf_1_glance","ref=dp_start-ubbf_1_glance");b.attr("action",c);return!0});n.when("a-popover").execute(function(b){var c=a("#usedItemConditionInfoLink"),d=b.create(c,{width:250,position:"triggerBottom",activate:g.capabilities.touch?
"onmousemove":"onclick",closeButton:!1,popoverLabel:"Used condition details",name:"usedItemConditionDetailsPopover",dataStrategy:"preload"});c.mouseleave(function(){d.hide()})})},initialize:function(){a(".rbbHeaderLink").attr("href","javascript:void(0);");a("#rbbContainer .rbbSection.unselected .dp-accordion-inner").hide();a("#rbbContainer .rbbSection .rbbHeader").click(function(b){a(b.target);b=a(this);var c=b.hasClass("rbbHeader")?b:b.parents(".rbbHeader");if(c.parents(".rbbSection").hasClass("selected"))return!1;
b=a("#rbbContainer .rbbSection.selected .rbbHeader").attr("id");var e=c.attr("id");d.updateCssClass(c);a("#abbWrapper [id^=mbb-offeringID-]").each(function(){this.checked=!1});c=a(this);d.animate(c);g.trigger("buybox:accordion:changed",e,b);return!0});d.oneClickJS();d.usedBuyBoxJS()}};return d})});
/* ******** */
(function(a){var c=window.AmazonUIPageJS||window.P,d=c._namespace||c.attributeErrors,b=d?d("DetailPagePromotionalBundleAssets",""):c;b.guardFatal?b.guardFatal(a)(b,window):b.execute(function(){a(b,window)})})(function(a,c,d){a.when("A","ready").execute("kbpMobileExpander",function(b){var a=b.$;a(".pb-bundle-section-expander").click(function(b){a(".pb-bundle-mobile-box").removeClass("aok-hidden");a(".pb-bundle-expander-box").addClass("aok-hidden")})})});
/* ******** */
