(function(g){var k=window.AmazonUIPageJS||window.P,q=k._namespace||k.attributeErrors,b=q?q("CustomerReviewsCommonAssets"):k;b.guardFatal?b.guardFatal(g)(b,window):b.execute(function(){g(b,window)})})(function(g,k,q){g.when("A","cr-log-utils","cr-uri-utils").register("cr-ajax-model",function(b,a,c){function d(a){var b=c.getUrlParametersMap()||{};b["overrides-marketplace-id"]&&(a=c.addKeyValuePair(a,"overrides-marketplace-id",b["overrides-marketplace-id"]));return a}function h(a){l[a]&&(l[a].abort(),
delete l[a])}function f(c,u,r,p,g,q,D){var F;F=q?q:t=t++;q=F;g=g?g:u.error||function(){};p=p?p:0;r=r?r:3;var z=u.finallyCallback||function(){};c=d(c);D||(D="reviewsAjax"+e++,k.uet&&k.uet("tc",D));u.params.scope=D;u.contentType="application/x-www-form-urlencoded;charset=UTF-8";var w=u.success||function(){};u.success=function(a){delete l[q];"function"===typeof w&&w(a);"function"===typeof z&&z(a)};u.error=function(b){h(q);p++;p<r?(a.logError("AJAX Post to "+c+" failed, Attempt: "+p+" out of "+r,"WARN"),
f(c,u,r,p,g,q,D)):(a.logError("AJAX Post to "+c+" from "+k.location.href+" failed, exhausted "+r+" attempts","FATAL"),"function"===typeof g&&g(b),"function"===typeof z&&z(b))};l[q]=b.post(c,u);return q}var e=0,t=1,l={};return{abort:h,post:f}});g.when("A","jQuery","cr-log-utils","cr-number-utils").register("cr-A",function(b,a,c,d){var h={top:-100,left:-100};b.inView=function(b){b=b||a();if("function"===typeof b.offset){var c=(b.offset()||h).top-a(k).scrollTop();b=0<=c;c=c<a(k).height();
return b&&c}return!1};b.onScreenAndVisible=function(b,c){b=b||a();var h=d.isFiniteNumber(c)?c:0;if(b instanceof a||b.jquery){if(!b.is(":visible"))return!1;var l=b[0].getBoundingClientRect();return l.top>=0-h&&l.left>=0-h&&l.bottom<=a(k).height()+h&&l.right<=a(k).width()+h}return!1};b.compositeEventWrapper=function(a,d,h){var l=a;h&&(l=b.throttle(l,h,{trailing:!1}));return c.jsGuard(function(a){a&&(l(a),d&&a.$event&&a.$event.preventDefault())})};return b});g.declare("reviews-constants",
{PUSH_STATE:!0,REPLACE_STATE:!1,RATING_SERVICE_CONTEXT_ID:"ReviewsConsumption",data:{REFTAG:"data-reftag",CSM_COUNTER:"data-csm-counter",getReviews:{STANDARD:"data-reviews-state-param",CHECKED:"data-reviews-param-checked",UNCHECKED:"data-reviews-param-unchecked"}},events:{CONTENT_CHANGED:"reviews:content-changed",RELOAD:"reviews:content-reload",RELOAD_COMPLETE:"reviews:content-reload-complete",AUTOSCROLL_COMPLETE:"reviews:autoscroll-complete",FILTER_FIRE_AGGREGATE:"reviews:filter-action:aggregate:trigger",
FILTER_FIRE_UPDATE:"reviews:filter-action:trigger",FILTER_AGGREGATE:"reviews:filter-action:aggregate",FILTER_PUSH:"reviews:filter-action:push-state",FILTER_REPLACE:"reviews:filter-action:replace-state",PAGINATION:"reviews:page-action",SEARCH_TEXTBOX:"reviews:search-textbox",SEARCH_BUTTON:"reviews:search-button",VOTE:"reviews:vote-action",TOGGLE_CLASS_CLICK:"reviews:toggle-class:click",AJAX_POST:"reviews:ajax-post",FILTER_APPLY:"reviews:filter-action:apply",FILTER_CHANGE:"reviews:filter-action:change",
FILTER_TAB_CLICKED:"reviews:filter-action:tab-clicked",FILTER_APPLY_BEGIN:"reviews:filter-action:apply-begin",FILTER_APPLY_SUCCESS:"reviews:filter-action:apply-success",FILTER_APPLY_ERROR:"reviews:filter-action:apply-error",FILTER_APPLY_DONE:"reviews:filter-action:apply-done",INPUT_COMMENT:"reviews:input-comment",SUBMIT_COMMENT:"reviews:submit-comment",OPEN_SUBMISSION_COMMENT:"reviews:open-comment-submission",SORT_COMMENTS:"reviews:sort-comments",MORE_COMMENTS:"reviews:more-comments",EDIT_COMMENT:"reviews:edit-comment",
CANCEL_EDIT_COMMENT:"reviews:cancel-edit-comment",DELETE_COMMENT:"reviews:delete-comment",SUBMIT_EDIT_COMMENT:"reviews:submit-edit-comment",MODIFY_EDIT_COMMENT:"reviews:modify-edit-comment",INPUT_PRODUCT_LINK:"reviews:input-product-link",SELECT_PRODUCT_LINK:"reviews:select-product-link",FEEDBACK_CLICK:"reviews:skyfall-feedback-click",CLIQUE_CLICK:"reviews:skyfall-clique-click",STAR_RATING_CLICK:"ryp:star-rating-click",STAR_RATING_CLEAR:"ryp:star-rating-clear-click"},filterOptions:{SORT_KEY:"sortBy",
HELPFUL:"helpful",RECENT:"recent",LEGACY_HELPFUL:"byRankDescending",LEGACY_RECENT:"bySubmissionDateDescending",MOBILE_HELPFUL:"sh",MOBILE_RECENT:"sd",STAR_KEY:"filterByStar",ALL_STARS:"all_stars",ONE_STAR:"one_star",TWO_STAR:"two_star",THREE_STAR:"three_star",FOUR_STAR:"four_star",FIVE_STAR:"five_star",POSTIVE:"positive",CRITICAL:"critical",FORMAT_KEY:"formatType",ALL_FORMATS:"all_formats",CURRENT_FORMAT:"current_format",AVP_KEY:"reviewerType",ALL_REVIEWS:"all_reviews",AVP_ONLY:"avp_only_reviews",
MEDIA_KEY:"mediaType",ALL_CONTENTS:"all_contents",MEDIA_ONLY:"media_reviews_only"},keycodes:{ENTER:13,BACK_SPACE:8,SPACE:32},aui:{HIDDEN:"aok-hidden",NOWRAP:"aok-nowrap"}});g.when("A","cr-string-utils","cr-log-utils").register("cr-popup",function(b,a,c){function d(d){var f={};d&&d.data&&(f=d.data);var e=a.defaultIfBlank(f.url,d.$target.find("a").andSelf().filter("a").attr("href")),g=a.defaultIfBlank(f.title,"CustomerReviews"),g=""+g,l="";b.each({width:"500",height:"500",resizable:"1",
scrollbars:"1",toolbar:"0",status:"1"},function(b,c){var d=a.defaultIfBlank(f[c],b);l+=c+"="+d+","});var l=l.slice(0,-1),n=null;try{(n=k.open(e,g,l))?n.focus():c.logError("Unable to move focus to popup window with data: "+a.stringify(f),"ERROR"),d.$event.preventDefault()}catch(u){c.logError("Unable to open window with parameters: "+a.stringify(f),"FATAL",u)}return n}b.declarative("cr-popup",["click"],c.jsGuard(d));return{popup:d}});g.when("A","jQuery","reviews-constants","cr-ajax-model",
"cr-string-utils").register("cr-generic-declarative-actions",function(b,a,c,d,h){function f(b){g(b)&&b.data.selector&&b.data.cssClass&&(a(b.data.selector).toggleClass(b.data.cssClass),b.$event.preventDefault())}function e(c){if(g(c)&&c.data.url&&c.data.params){c.$event.preventDefault();b.declarative.remove(c.$currentTarget,n.AJAX_POST);c=c.data;var e=c.params,f=a(c.indicatorSelector)[0],h=l(a.fn.hide,c.hideOnSuccessSelector),k=l(a.fn.show,c.showOnFailureSelector);a(c.removeOnLoadSelector).remove();
d.post(c.url,{params:e,indicator:f,success:h,error:k})}}function g(a){return a&&a.data&&a.$event&&"function"===typeof a.$event.preventDefault}function l(b,c){if(c&&"function"===typeof b)return function(){var d=a(c);0<d.length&&b.call(d)}}var n=c.events;b.declarative(n.TOGGLE_CLASS_CLICK,"click",f);b.declarative(n.AJAX_POST,"click",e);return{toggleCssClass:f,ajaxPost:e}});g.when("A","ready").register("cr-global-model",function(b){var a=b.state("reviews-page-state");a||(a=b.$("#cr-state-object").data("state"));
var c=null;a&&(c=a.customerId);return{generateUrl:function(a,b){var c=a;c&&"/"!==c.charAt(c.length-1)&&(c+="/");c&&b&&(c=c+"ref="+b);return c},isSignedIn:function(){return c?!0:!1}}});g.when("A","a-expander","jQuery","reviews-constants","cr-string-utils").register("cr-global-view",function(b,a,c,d,h){function f(a){var b="";if(a&&a.closest!==q){var c=a.closest("*["+u.REFTAG+"]");c&&(b=c.attr(u.REFTAG))}h.isBlank(b)&&a&&a.closest!==q&&(a=a.closest("*[rel]"))&&(b=a.attr("rel"));return h.defaultIfBlank(b,
"cm_cr_unknown")}function e(a){return a&&"function"===typeof a.is?a.is("*["+u.getReviews.CHECKED+"]")&&a.is("*["+u.getReviews.UNCHECKED+"]"):!1}function g(a){return a&&a.has!==q&&a.is!==q?0<a.find(":checked").length||a.is(":checked"):!1}function l(a,b){return a&&a.attr!==q&&b?h.parseJSON(a.attr(b))||{}:{}}function n(a){return a!==q}var u=d.data;b.on("a:expander:review_text_read_more:toggle:collapse",function(a){n(a)&&n(a.expander)&&n(a.expander.$expander)&&1===a.expander.$expander.length&&n(a.expander.$expander[0].closest(".review"))&&
n(a.expander.$expander[0].closest(".review").offsetTop)&&(a=a.expander.$expander[0].closest(".review").offsetTop,k.scroll(0,a))});b.on("a:pageUpdate",function(){n(a)&&a.initializeExpanders()});return{getReviewsStateParamsFromElement:function(a){var c=b.reduce(u.getReviews,function(a,b){return a+"*["+b+"],"},"").slice(0,-1),d;c&&a&&a.closest!==q&&(d=a.closest(c));return e(d)?g(d)?l(d,u.getReviews.CHECKED):l(d,u.getReviews.UNCHECKED):l(d,u.getReviews.STANDARD)},getReftag:function(a){var b;a&&a.$target&&
(b=a.$target);a&&a.id&&(b=c("#"+a.id));a&&a.expander&&a.expander.$expander&&(b=a.expander.$expander);b=f(b);"cm_cr_unknown"===b&&a&&a.data&&a.data.reftag&&(b=a.data.reftag);return b},getReftagByDom:f,scrollTo:function(a,b){var d=c(a).offset(),e=b||0,h=c("#cr-state-object").data("state"),h=h!==q&&h.disableScroll;d&&d.top!==q&&!h&&(c("html,body").stop(),c("html,body").animate({scrollTop:d.top-e},{queue:!1,duration:500}))}}});g.when("A").register("cr-log-utils",function(b){function a(a,
b,c){k.ueLogError&&("string"!==typeof b&&(b="FATAL"),c?k.ueLogError(c,{message:a,logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}):k.ueLogError({message:a},{logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}))}function c(a,b){return"string"===typeof b?b+a:"CustomerReviews:"+a}return{logError:a,jsGuard:function(b){if("function"===typeof b)return function(){try{return b.apply(this,arguments)}catch(c){a("Uncaught Error in function","FATAL",c)}};a("Unable to wrap non-function","ERROR");
return b},incrementCount:function(a,b){if(k.ue){var f=c(a,b),e=k.ue.count(f)||0;k.ue.count(f,e+1)}},logCount:function(a,b,f){k.ue&&(a=c(a,f),k.ue.count(a,b))}}});g.register("cr-mash-utils",function(){var b=!1;g.when("mash").execute(function(){b=!0});return{isMash:function(){return b}}});g.when("A","cr-log-utils").register("cr-number-utils",function(b,a){return{convertToInteger:function(b,d){if(b===parseInt(b,10))return b;if(null!==b&&b!==q&&""!==b)return parseInt(b.replace(/[^0-9]/g,
""),10);if(d!==q)return d;a.logError("convertToInteger","Cannot convert "+b+" to Integer");return 0},isFiniteNumber:function(a){return"number"===typeof a&&!isNaN(a)&&isFinite(a)}}});g.when("cr-A","jQuery","cr-string-utils","afterReady").register("cr-on-view-utils",function(b,a,c){function d(a,c){if(!e[a]){var d=h(a,c)();g[a]=(g[a]||[]).concat(d);b.on.scroll(d)}}function h(c,d){return function r(){b.inView(a(c))&&(f(c,d),b.each(g[c]||[],function(a){b.off("scroll",a)}));return r}}function f(a,
c){e[a]||(e[a]=!0,b.post(c.ajaxUrl,{params:c.ajaxParamsMap||{}}))}var e={},g={};b.each(a("*[data-cr-trigger-on-view]"),function(b,e){var f=a(b),h=f.attr("data-cr-trigger-on-view"),h=c.parseJSON(h);if(null!==h){var g="cr-trigger-on-view-"+e;f.addClass(g);d("."+g,h)}});return{triggerOnScrollIntoView:d,trigger:f}});g.when("A","jQuery").register("cr-streaming-utils",function(b,a){return{appendFadeIn:function(c){if(null!==c&&2<c.length&&null!==c[1]&&null!==c[2]){var d=c[1];c=a(c[2]).hide();
a(d).append(c);b.fadeIn(c,500,"ease-in-out",function(){})}},replace:function(b){if(null!==b&&2<b.length&&null!==b[1]&&null!==b[2]){var d=b[2];a(b[1]).replaceWith(a(d))}}}});g.when("A","cr-log-utils").register("cr-string-utils",function(b,a){function c(a){return null===a||a===q?!0:0===b.trim(a).length}return{defaultIfBlank:function(a,b){return c(a)?b:a},isBlank:c,parseJSON:function(c){try{return b.parseJSON(c)}catch(h){a.logError("Unable to parse JSON object","ERROR",h)}return null},startsWith:function(a,
b){return a===b?!0:null===a||null===b?!1:0===a.indexOf(b)},stringify:function(a){return k.JSON&&k.JSON.stringify?k.JSON.stringify(a):a}}});g.when("A").register("cr-uri-utils",function(b){function a(a){a=a||k.location.href;var d={},h=a.indexOf("?"),f=a.indexOf("#");a=a.slice(h+1,f>h?f:q)||"";h=[];-1<a.indexOf("&")?h=a.split("&"):-1<a.indexOf("=")&&(h=[a]);b.each(h,function(a,b){if(0<a.indexOf("=")){var c=a.split("=");d[c[0]]=c[1]}});return d}return{getUrlParametersMap:a,addKeyValuePair:function(b,
d,h){h=h||0;if(a(b)[d]===h||!b||!d)return b;d="?"+d+"="+h;return-1<b.indexOf("?")?b.replace("?",d+"&"):b+d}}});g.when("A","cr-uri-utils","cr-string-utils","3p-urijs").register("cr-extended-uri-utils",function(b,a,c,d){function h(){return d(k.location.href)}function f(){return h().query()}return b.$.extend(a,{getCurrentUri:h,getCurrentQueryString:f,getCurrentQueryParameters:function(){return d.parseQuery(f())},isAmazonDomain:function(a){if("string"===typeof a||a instanceof String)a=d(a);
var b=c.startsWith(a.domain(),"amazon");!1===b&&(a=a.hostname(),a=a.substring(a.indexOf(".")+1),b=c.startsWith(a,"amazon"));return b},setQueryParameters:function(a,f){if("string"===typeof a||a instanceof String)a=d(a);b.each(f,function(b,d){c.isBlank(b)?a.removeSearch(d):a=a.setSearch(d,b)});return a},setReftag:function(a,b){if("string"===typeof a||a instanceof String)a=d(a);for(var f=a.segment(),h=!1,g=f.length-1;0<=g;g--)if(c.startsWith(f[g],"ref=")){h=!0;f[g]="ref="+b;break}h||f.push("ref="+b);
a.segment(f);return a}})});g.when("cr-A","jQuery","cr-log-utils","cr-string-utils","afterReady").register("cr-weblab-utils",function(b,a,c,d){function h(d,e,h,p){g[e]||(c.logCount(h,0,p),d=f(a(d),e,h,p)(),l[e]=(l[e]||[]).concat(d),b.on.scroll(d))}function f(a,c,d,f){return function y(){b.inView(a)&&(e(c,d,f),b.each(l[c]||[],function(a){b.off("scroll",a)}));return y}}function e(a,d,e){if(!g[a]){g[a]=!0;var f=b.$("#cr-state-object").data("state");b.post(f.weblabTriggerUrl,{params:{weblabId:a}});
c.logCount(d,1,e)}}var g={},l={};b.each(a("*[data-cr-weblab-trigger-on-scroll]"),function(b,c){var e=a(b),f=e.attr("data-cr-weblab-trigger-on-scroll"),f=d.parseJSON(f);if(null!==f){var l="cr-weblab-trigger-on-scroll-"+c;e.addClass(l);h("."+l,f.weblabId,f.metricName,f.prefix)}});return{triggerOnScrollIntoView:h,triggerWeblab:e}});g.when("A").register("histogram-trigger",function(b){function a(){b.onScreen(b.$("#histogramTable"))&&b.trigger("scroll")}b.on.afterLoad(a);return{triggerHistogram:a}})});
/* ******** */
(function(g){var k=window.AmazonUIPageJS||window.P,q=k._namespace||k.attributeErrors,b=q?q("CustomerReviewsMedleyAssets"):k;b.guardFatal?b.guardFatal(g)(b,window):b.execute(function(){g(b,window)})})(function(g,k,q){g.when("A","medley-view","medley-model","ready").register("medley-controller",function(b,a,c){function d(b){b=c.getASIN();var d=a.getDisplayedASIN();d&&b!==d&&(a.fadeReviews(!0),c.getReviews(d,function(){c.setASIN(d)},function(){},function(){a.fadeReviews(!1)}))}var h=a.getLoadedASIN();
c.setASIN(h);b.on("a:pageUpdate",d);return{onTwist:d}});g.when("A","jQuery").register("medley-view",function(b,a){return{getDisplayedASIN:function(){return String(a("#ASIN").val()||"")},getLoadedASIN:function(){return(b.$("#cr-state-object").data("state")||{}).asin||""},fadeReviews:function(b){!1===b?a("#cm-cr-review-list .review,#most-recent-reviews-content .review").css("opacity",1):a("#cm-cr-review-list .review,#most-recent-reviews-content .review").css("opacity",.5)}}});
g.when("A","cr-global-model","cr-ajax-model","cr-uri-utils").register("medley-model",function(b,a,c,d){function h(a){var b=d.getUrlParametersMap()||{};b.asin=a;return b}var f;return{setASIN:function(a){f=a||""},getASIN:function(){return f},getReviews:function(a,d,f,g){var k=b.$("#cr-state-object").data("state");"string"===typeof a&&10===a.length?c.post(k.medleyReviewsAjaxUrl,{params:h(a),attribution:"getMedleyReviews",success:d,error:f,finallyCallback:g}):"function"===typeof g&&g()}}});
g.when("A","review-skyfall-view","review-skyfall-model","reviews-constants","cr-global-view","a-button").register("review-skyfall-shared-controller",function(b,a,c,d,h,f){function e(a){a=h.getReftag(a);c.clickMetric(a,function(){})}function g(b,d){a.showMoreFeedbackSection(b.$target.closest(".feedback-section"));var e=h.getReftag(b);c.clickMetric(e,b.data,function(a){d.disable()})}b.declarative(d.events.FEEDBACK_CLICK,"click",function(a){var b=f(".cr-feedback-helpful-yes, .cr-feedback-helpful-no");
g(a,b)});b.declarative(d.events.CLIQUE_CLICK,"click",e);return{feedbackClick:g,cliqueClick:e}});g.when("A","cr-log-utils").register("review-skyfall-controller",function(b,a){b.on("a:expander:clique-ratings-read-more:toggle:expand",function(b){a.incrementCount("desktopSkyfallReadMore")});b.on("a:popover:show:skyfallWhatsThis",function(b){a.incrementCount("desktopSkyfallWhatsThis")})});g.when("A","cr-ajax-model","cr-global-model").register("review-skyfall-model",function(b,
a,c){return{clickMetric:function(d,h,f){var e=b.$("#cr-state-object").data("state");d=c.generateUrl(e.reftagTriggerUrl,d);a.post(d,{params:h,success:f})}}});g.when("A","reviews-constants").register("review-skyfall-view",function(b,a){return{showMoreFeedbackSection:function(b){b.find(".more-feedback-section").removeClass(a.aui.HIDDEN);b.find(".is-feature-helpful-row").addClass(a.aui.HIDDEN)}}})});
/* ******** */
(function(g){var k=window.AmazonUIPageJS||window.P,q=k._namespace||k.attributeErrors,b=q?q("CustomerReviewsVotingAssets"):k;b.guardFatal?b.guardFatal(g)(b,window):b.execute(function(){g(b,window)})})(function(g,k,q){g.when("A","vote-model","vote-view","a-modal").register("vote-controller",function(b,a,c,d){function h(a,b){f(a,b);c.showElementByCssSelector(a,b.inFlight)}function f(a,b){c.hideElementByCssSelector(a,b.hideVoteComponents);b.hideAbuseComponents&&c.hideElementByCssSelector(a,b.hideAbuseComponents)}
function e(e,g){g.isReportAbuse&&(e=b.$("#mobile-abuse-"+g.voteInstanceId),d.get(e).hide());h(e,g.cssSelectors);a.submitVote(g.ajaxUrl,g.voteValue,g.voteInstanceId,g.csrfT,g.voteDimension,function(a){if(!0===a){a=e;var b=g.cssSelectors;f(a,b);c.showElementByCssSelector(a,b.onSuccess)}else a=e,b=g.cssSelectors,f(a,b),c.showElementByCssSelector(a,b.onError)},function(){var a=e,b=g.cssSelectors;f(a,b);c.showElementByCssSelector(a,b.onError)})}b.declarative("reviews:vote-action","click",function(a){e(a.$target,
a.data);a.$event.preventDefault()});return{submitVote:e}});g.when("A","cr-ajax-model").register("vote-model",function(b,a){return{submitVote:function(b,d,h,f,e,g,k){a.post(b,{params:{voteInstanceId:h,voteValue:d,csrfT:f,voteDimension:e},attribution:"submitVote",success:g,error:k})}}});g.when("A").register("vote-view",function(b){function a(a,b){return a.closest(".cr-vote").find(b)}return{hideThankYouAlert:function(b){a(b,".cr-vote-success").addClass("aok-hidden")},showThankYouAlert:function(b){a(b,
".cr-vote-success").removeClass("aok-hidden")},showErrorAlert:function(b){a(b,".cr-vote-error").removeClass("aok-hidden")},showFeedback:function(b){a(b,".cr-vote-feedback").removeClass("aok-hidden")},hideFeedback:function(b){a(b,".cr-vote-feedback").addClass("aok-hidden")},hideButtons:function(b){a(b,".cr-vote-buttons").addClass("aok-hidden")},hideElementByCssSelector:function(b,d){a(b,d).addClass("aok-hidden")},showElementByCssSelector:function(b,d){a(b,d).removeClass("aok-hidden")}}})});
/* ******** */
(function(g){var k=window.AmazonUIPageJS||window.P,q=k._namespace||k.attributeErrors,b=q?q("CustomerReviewsGalleryAssets"):k;b.guardFatal?b.guardFatal(g)(b,window):b.execute(function(){g(b,window)})})(function(g,k,q){g.when("A","load").register("review-image-asset-loader",function(b){var a=!1;b.ajax("/gp/customer-reviews/aj/private/reviewsGallery/get-image-gallery-assets",{method:"post",success:function(b){g.load.css(b.reviewsLightboxCSS);var d=document.createElement("script");d.type="text/javascript";
d.async=!0;d.setAttribute("crossorigin","anonymous");d.src=b.reviewsLightboxJS;document.getElementsByTagName("head")[0].appendChild(d);a=!0;g.register("review-image-assets-loaded",{})},error:function(){var a;a="/gp/customer-reviews/aj/metrics/log-values?noCache="+(new Date).getTime();a+="&SimpleStack:ReviewImageAssetLoaderFailure=1";k.Image&&((new Image).src=a)}});return{isLoaded:function(){return a}}});g.when("A","jQuery","cr-log-utils","reviews-constants","review-image-assets-loaded").register("review-image-binder",
function(b,a,c,d){function h(b,d,e,h,k){if(!(b&&d&&e instanceof a&&h instanceof a&&k instanceof a))return c.logError("Invalid parameters for imageBinder.initializeEventHandlers with ASIN: "+b+", galleryName: "+d+", $popoverTrigger: "+e+", $thumbnails: "+h+", $galleryLink: "+k,"FATAL"),!1;var q="reviewsLightbox-ready-"+d;h.click(function(){f(b,d);var c=h.index(this);e.click();g.when(q).execute(function(){a("#"+d).trigger("jumpToImageAtIndex",c)})});k.click(function(){f(b,d);e.click();g.when(q).execute(function(){a("#"+
d).trigger("hideImmersiveView")})});return!0}function f(a,b){if(!a||!b)return c.logError("Invalid parameters for imageBinder.initializeImageGallery with ASIN: "+a+", galleryName: "+b,"FATAL"),!1;if(e)return!0;(new ReviewsLightbox(b,"DESKTOP")).initializeForAsin(a);return e=!0}var e=!1,k={};g.when("reviewsLightbox-js").execute(function(){var b=a("#reviews-image-gallery-container"),c=b.attr("data-asin");0<b.length&&c&&h(c,"reviews-image-gallery",b.find(".a-popover-trigger"),b.find(".review-image-tile"),
b.find(".reviews-image-gallery-link"))});b.on(d.events.RELOAD_COMPLETE,function(){k={}});return{bindReview:function(b,c,d){var e=new ReviewGallery(d,"DESKTOP"),f=a("#"+c);f.find(".review-image-tile").each(function(c){a(this).click(function(){k[b]||(e.initializeForReview(b),k[b]=!0);f.find(".a-popover-trigger").click();g.when("reviewsLightbox-ready-"+d).execute(function(){e.render();e.showImageAtIndex(c)})})})},initializeImageGallery:f,initializeEventHandlers:h}});g.when("A","jQuery",
"cr-video-model","cr-video-view","reviews-constants").register("cr-video-controller",function(b,a,c,d,h){function f(){b.each(a(".review-views .review"),function(a,b){if(a&&a.id){var f=c.getEmbedInfo(a.id);f&&d.embedVideo(f)}})}b.on(h.events.RELOAD_COMPLETE,function(){f()});f();return{initAll:f}});g.when("jQuery").register("cr-video-model",function(b){return{getEmbedInfo:function(a){var c="video-block-"+a,d=b("#"+a+" .video-url").val(),h=b("#"+a+" .video-slate-img-url").val(),f=b("#cr-video-swf-url").val();
return a&&d&&f?{videoDomId:c,videoUrl:d,videoSlateImgUrl:h,videoSwfUrl:f}:!1}}});g.when("jQuery","afterLoad").register("cr-video-view",function(b){g.now("Airy").execute(function(a){var c=b("#cr-airy-js-source-url").val(),d=b("#cr-airy-css-source-url").val();a||"string"!==typeof c||"string"!==typeof d||(g.load.js(c),g.load.css(d))});return{embedVideo:function(a){g.when("Airy").execute(function(b){b.embed({parentId:a.videoDomId,streamingUrls:[a.videoUrl],slateImages:{preloadSlate:a.videoSlateImgUrl},
swfUrl:a.videoSwfUrl,desiredMode:"html"})})}}})});
/* ******** */
(function(g){var k=window.AmazonUIPageJS||window.P,q=k._namespace||k.attributeErrors,b=q?q("CustomerReviewsFilteringAssets"):k;b.guardFatal?b.guardFatal(g)(b,window):b.execute(function(){g(b,window)})})(function(g,k,q){g.when("cr-A","jQuery","cr-filtering-view","cr-filtering-model","cr-global-view","reviews-constants","cr-streaming-utils","cr-log-utils").register("cr-filtering-controller",function(b,a,c,d,h,f,e,g){function l(a){var b=!1,c=!1;a.toggleFilters&&(c=!0);b=d.setReviewerType(a.reviewerType,
c)||b;b=d.setFormatType(a.formatType,c)||b;b=d.setFilterByKeyword(a.filterByKeyword,c)||b;b=d.setFilterByLanguage(a.filterByLanguage,c)||b;b=d.setSortOrder(a.sortOrder,c)||b;b=d.setStarFilter(a.filterByStar,c)||b;return b=d.setPageNumber(a.pageNumber,c)||b}function n(a){l(a.data)&&(c.hideReviewLoadError(),c.hideReviews(),c.showLoadingSpinner(),b.trigger(f.events.FILTER_APPLY_BEGIN,a),d.getReviews(function(){c.showReviews();b.trigger(f.events.FILTER_APPLY_SUCCESS,a)},function(){c.showReviewLoadError();
b.trigger(f.events.FILTER_APPLY_ERROR,a)},function(){c.hideLoadingSpinner();b.trigger(f.events.FILTER_APPLY_DONE,a);b.trigger(f.events.RELOAD_COMPLETE)},function(a){"appendFadeIn"===a[0]?e.appendFadeIn(a):"replace"===a[0]&&e.replace(a)},h.getReftag(a)),a.data.scrollToSelector&&h.scrollTo(a.data.scrollToSelector,0))}function u(a){a&&a.data&&n(a)}function k(a){a&&a.data&&a.$target&&a.data.filterType&&(a.data[a.data.filterType]=a.$target.val(),n(a))}function p(a){a&&a.data&&a.data.filterType&&(c.deactivateFilterTabHeaders(),
c.activateFilterTabHeader(a.data.filterType))}d.setASIN(c.getLoadedASIN());d.setReviewsAjaxUrl(c.getReviewsAjaxUrl());b.declarative(f.events.FILTER_APPLY,"click",b.compositeEventWrapper(u,!0,100));b.declarative(f.events.FILTER_CHANGE,"change",b.compositeEventWrapper(k,!0,100));b.declarative(f.events.FILTER_TAB_CLICKED,"click",p);return{setFilterParams:l,onFilterApply:u,onFilterChange:k,onFilterTabClicked:p}});g.when("A","cr-ajax-model","ready").register("cr-filtering-model",function(b,
a){function c(){return e.asin||""}function d(){return g||""}function h(a,b){b?e[a]=b:delete e[a]}function f(a,b,c){var d=!1;a&&b!==q&&(d=(e[a]||"")!==b,!d&&c&&(b="",d=!0),h(a,b));return d}var e={},g="",l;return{getReviews:function(b,c,d,f,h){var k=g;l&&a.abort(l);h&&(k+="ref="+h);l=a.post(k,{params:e,attribution:"getFilteredReviews",success:b,error:c,finallyCallback:function(){d();l=0},chunk:f})},setASIN:function(a){var b=c()!==a;h("asin",a);return b},getASIN:c,setReviewsAjaxUrl:function(a){var b=
d()!==a;g=a||"";return b},getReviewsAjaxUrl:d,setReviewerType:function(a,b){return f("reviewerType",a,b)},getReviewerType:function(){return e.reviewerType||""},setFormatType:function(a,b){return f("formatType",a,b)},getFormatType:function(){return e.formatType||""},setFilterByKeyword:function(a,b){return f("filterByKeyword",a,b)},getFilterByKeyword:function(){return e.filterByKeyword||""},setFilterByLanguage:function(a,b){return f("filterByLanguage",a,b)},getFilterByLanguage:function(){return e.filterByLanguage||
""},setSortOrder:function(a,b){return f("sortBy",a,b)},getSortOrder:function(){return e.sortBy||""},setStarFilter:function(a,b){return f("filterByStar",a,b)},getStarFilter:function(){return e.filterByStar||""},setPageNumber:function(a,b){return f("pageNumber",a,b)},getPageNumber:function(){return e.pageNumber||""},getFilterParams:function(){return e||{}},updateFilterParam:h}});g.when("A","jQuery","ready").register("cr-filtering-view",function(b,a){return{getLoadedASIN:function(){return(a("#cr-state-object").data("state")||
{}).asin||""},getReviewsAjaxUrl:function(){return(a("#cr-state-object").data("state")||{}).reviewsAjaxUrl||""},showLoadingSpinner:function(){a(".cr-reviews-loading").removeClass("aok-hidden")},hideLoadingSpinner:function(){a(".cr-reviews-loading").addClass("aok-hidden")},hideReviews:function(){a(".filterable-reviews-content").addClass("aok-hidden")},showReviews:function(){a(".filterable-reviews-content").removeClass("aok-hidden")},showReviewLoadError:function(){a(".review-load-error").removeClass("aok-hidden")},
hideReviewLoadError:function(){a(".review-load-error").addClass("aok-hidden")},deactivateFilterTabHeaders:function(){a(".cr-tab-header-text").removeClass("cr-tab-active")},activateFilterTabHeader:function(b){a(".cr-tab-header-text-"+b).addClass("cr-tab-active")}}});g.when("cr-A","cr-lighthut-terms-view","reviews-constants","cr-log-utils").register("cr-lighthut-terms-controller",function(b,a,c,d){function h(b){b&&b.filterByKeyword!==q&&(a.setSelected(b.filterByKeyword),d.incrementCount("LighthutTermClicked"))}
b.on(c.events.FILTER_APPLY_BEGIN,b.compositeEventWrapper(function(a){a&&a.data&&h(a.data)}));return{onFilterApplied:h}});g.when("A","jQuery","ready").register("cr-lighthut-terms-view",function(b,a){return{setSelected:function(b){b=b.replace(/ /g,"_");var d=(b=a("#cr-lighthouse-term-"+b))&&b.hasClass("cr-lighthut-term-selected");a(".cr-lighthut-term-selected").removeClass("cr-lighthut-term-selected");d||b.addClass("cr-lighthut-term-selected")}}})});
/* ******** */
