(function(c){var d=window.AmazonUIPageJS||window.P,e=d._namespace||d.attributeErrors,a=e?e("MASDetailPageAssets"):d;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,d,e){c.when("A","ready").execute(function(a){var b=a.$;b.fn.scrollIntoView=function(){return this.each(function(){b("html, body").animate({scrollTop:b(this).offset().top},1E3)})};b(".a-js .scroll-fragment").bind("click",function(a){a.preventDefault();a=b(this).attr("href");b(a).scrollIntoView()})});
c.when("A","a-modal","ready").execute(function(a,b){var c=a.$;a.declarative("buy_box_warning_submit","click",function(a){c("#handleBuy").submit()})});c.when("A","jQuery").execute(function(a,b){b(document).ready(function(){var a=b("#masBuyBoxOneClickInput"),c=b("#masBuyBoxZeroesInput"),d=b("#masBuyBoxOneClickPaymentOption"),e=b("#masBuyBoxZeroesPaymentOption"),f=function(){"checked"===a.attr("checked")?(e.removeClass("selected"),d.addClass("selected")):(d.removeClass("selected"),e.addClass("selected"))};
f();a.click(f);c.click(f)})})});
/* ******** */
(function(n){var m=window.AmazonUIPageJS||window.P,t=m._namespace||m.attributeErrors,g=t?t("CommonDetailPageScripts"):m;g.guardFatal?g.guardFatal(n)(g,window):g.execute(function(){n(g,window)})})(function(n,m,t){n.when("jQuery","jumpLink").execute(function(g,a){var c=g("#miniATFUDP"),d=0;0<c.length&&(d=c.height()+9);1===m.isACRJumplLinkAnimated?a.bind("#acrCustomerWriteReviewLink, #acrCustomerReviewLink, #reviewLink, #reviewLinkShort, #reviewCreateLink",1E3,d):2===m.isACRJumplLinkAnimated?a.bind("#acrCustomerWriteReviewLink, #acrCustomerReviewLink, #reviewLink, #reviewLinkShort, #reviewCreateLink",
1200,d):3===m.isACRJumplLinkAnimated?a.bind("#acrCustomerWriteReviewLink, #acrCustomerReviewLink, #reviewLink, #reviewLinkShort, #reviewCreateLink",1400,d):4===m.isACRJumplLinkAnimated?a.bind("#acrCustomerWriteReviewLink, #acrCustomerReviewLink, #reviewLink, #reviewLinkShort, #reviewCreateLink",10,d):0<c.length&&(d=c.height()+9,a.bind("#acrCustomerWriteReviewLink, #acrCustomerReviewLink, #reviewLink, #reviewLinkShort, #reviewCreateLink",10,d));0<g("#reviewStarsLinkedCustomerReviews").length&&a.bind("#reviewStarsLinkedCustomerReviews",
10,d);0<g("#askATFLink").length&&a.bind("#askATFLink",10,d);n.when("cf").execute(function(b){0<g("#important-information a[href='#legal-disclaimer']").length&&a.bind("#important-information a[href='#legal-disclaimer']",10,d,!0)});a.bind("#seeMoreDetailsLink",300,d)});n.when("A","jQuery","ImageBlockATF","jumpLink","cf").register("miniATFUtils",function(g,a,c,d){function b(b){p&&!b||Y||(b=(new Date).getTime()-k,b=50>b?50-b:10,p=1,p=0,k=(new Date).getTime(),setTimeout(function(){var b=l.scrollTop(),
f=a("#miniATFUDP");if(0<f.length){var e=x;if("T1"===e){e=a("#sims_fbt");if(0>=e.length||0>=e.height())e=a("#buyxgety_feature_div");var g=e,e=Number.MAX_VALUE;if(g&&0<g.length){var c=g.height(),g=g.offset();c&&g&&(e=g.top+c)}e=Math.min(e,1200)}else if("T2"===e){e="#product-details-grid_feature_div #prodDetails #important-information_feature_div #importantInformation #detail-bullets #detail_bullets_id #technical-data #technicalSpecifications_feature_div #productDescription #product-description-iframe #dpx-btf-hlcx-comparison_feature_div #HLCXComparisonWidget_feature_div".split(" ");
g=Number.MAX_VALUE;for(c=0;c<e.length;c++){var d=a(e[c]);if(d&&0<d.length&&0<d.height()){var k;k=Number.MAX_VALUE;d&&0<d.length&&(d=d.offset())&&(k=d.top);k<g&&(g=k)}}e=Math.min(g,1700)-100}else e=void 0;b>e?!h&&f.is(":hidden")&&(f.removeClass("a-hidden"),f.slideDown(200)):(f.slideUp(200),h=0)}},b))}d=a("#miniATFUDP");var f=a("#miniATFPartialSelection")[0],e=a(".twister-dropdown-highlight")[0];if(!(0>=d.length)){var l,h=0,k=0,p=0,q={},Y=0,Q=0,x="T2";q.setMiniATFShowHeight=function(b){x=b};q.setMiniATFScrollUpHeight=
function(b){Q=0;"T1"===b&&(b=a("#productTitle"),0<b.length&&(b=b.offset())&&(Q=b.top-20))};a("body").delegate(".go-to-top","click",function(){a("body, html").animate({scrollTop:Q},300);h=1;f&&e&&(a(e).removeClass("transparentTwisterDropdownBorder"),a(e).addClass("highlightTwisterDropdownBorder"));return!1});f&&e&&a(e).click(function(){a(this).addClass("transparentTwisterDropdownBorder");a(this).removeClass("highlightTwisterDropdownBorder")});l=a(m);l.scroll(function(){b(0)});l.resize(function(){b(1)});
n.when("ImageBlockBTF").execute(function(b){var f=function(f){var e=f.getState().selected_variations;if(e){var g="",c=f.getState().variation_display_labels;a.each(b.visualDimensions,function(a,f){var l=1===b.gIsNewTwister?f:c[f];e[l]&&(g+=" "+e[l])});return g&&g.substring(1)}},e=b.defaultColor,l=e,h=b.landingAsinColor,d,k=a("#miniATF_image");0<k.length&&(d=k.attr("src"));q.updateMiniATFDiv=function(){Y=0;var b=a("#miniATF_image");0<b.length&&d&&b.attr("src",d)};g.on("image-block-twister-swatch-click",
function(a,g,k,p){Y=1;a=(a=p?p:f(g))&&""!==a?a:e;a===h&&(a=e);a!==l&&(d=(g=a!==e&&a!==h?b:c)&&g.colorImages&&g.colorImages[a]&&0<g.colorImages[a].length&&g.colorImages[a][0]?g.colorImages[a][0].large:null,l=a)})});return q}});n.when("ueCount","jQuery").execute(function(g,a){a("#miniATF_BackToTopLink").click(function(){g.incrementCounterByOne("sl_back_to_top_button_click_count")})});n.register("dp-util-cookie",function(){return function(g){g+="=";for(var a=decodeURIComponent(document.cookie).split(";"),
c=0;c<a.length;c++){var d=a[c],d=d.replace(/^\s+/,"");if(0===d.indexOf(g))return d.substring(g.length,d.length)}return""}});n.when("jQuery","dp-util-cookie","cf").execute(function(g,a){"000-0000000-8675309"===g("#addToCart").find('input[name="session-id"]').val()&&g("#addToCart").find('input[name="session-id"]').val(a("session-id"))})});
/* ******** */
