(function(m){var q=window.AmazonUIPageJS||window.P,r=q._namespace||q.attributeErrors,d=r?r("DetailPageTwisterViewAsset",""):q;d.guardFatal?d.guardFatal(m)(d,window):d.execute(function(){m(d,window)})})(function(m,q,r){m.when("A","dp-refresh-handler","view-util","twister-string-constants").register("page-refresh-view",function(d,D,n,l){var k=d.$;return function(u,p,r){function x(b){return{chunk:function(c){var b=c.ASIN,h=c.Value;c=c.FeatureName;"twister-slot-price_feature_div"==c&&((h=h?h.content:
null)&&""!==h.priceToSet&&k(".swatchSelect .twisterSwatchPrice").text(h.priceToSet),h&&h.hasPricePerUnit&&""!==h.pricePerUnitDisplay&&k(".swatchSelect .price_slot_ppu").text(h.pricePerUnitDisplay));f.twisterRefreshHandler.stampFeature(c,b)},success:function(c,b,h){y("twisterUpdateSuccess")},error:function(c,b,h){Twister.$("#variations-overlay").hide();y("twisterUpdateFailure");Twister.showErrorMessageOnFailure&&(alert(Twister.errorMessageOnFailure),location.reload())},abort:function(c){z.logFatal("Ajax aborted: "+
c)},timeout:4E4}}function A(b,c,e,h,a){var g=[];"parent"===b?(c=v(c,h,"parent",a),g.parent=c,c=v(e,h,"partial",a),g.partial=c):(c=v(e,h,b,a),g[b]=c);return g}function w(b,c,e,h,a){for(var g in b)if(b.hasOwnProperty(g)){if("full"===g){var d=e.dimensionType,k=f.twisterUtil.getDimensionInfo().length;f.twisterRefreshHandler.startMeasurement(e.newAsin,d,k,e.dimensionDisplayType)}d=b[g].twisterRefreshParams;k=b[g].notifyClientParams;a&&(f.twisterRefreshHandler.fadeInFeatures(f.config[g].affectedFeatures),
f.twisterRefreshHandler.doPageRefresh(d,c,h));E(k.asin,k.id,g,a)}}function F(){k.each(p.contextMetaData,function(b,c){var e={};c=c.elementList||[];var h=c.length,a=[];e.click={};e.mouseOver={};for(var g=0;g<h;g++){var d=k("#"+c[g].divToUpdate);a.push(c[g].divToUpdate);d.length&&c[g].customClientFunction&&(c[g].updateOnHover&&(e.mouseOver[c[g].divToUpdate]=d.attr("customfunctionname")),e.click[c[g].divToUpdate]=d.attr("customfunctionname"))}f.config[b].affectedFeatures=a;f.config[b].clientFeatures=
e})}function E(b,c,e,h){var a="",a=h?l.EVENT_TYPE_CLICK:l.EVENT_TYPE_MOUSEOVER;k.each(f.config[e].clientFeatures[a],function(a,h){try{var e=function(){f.twisterRefreshHandler.stampImageLoad(b)};(function(){var a={};a.P=m;(function(){eval("var P \x3d this.P;");eval("0, "+h)(c,DetailPage.StateController,e)}).call(a)})()}catch(d){z.logFatal("Client feature - "+a+", threw and exception :- "+d)}})}function v(b,c,e,h){var a={},g={},k={};a.isFlushing=2;a.dpEnvironment=Twister.dpEnvironment;a.asinList=b;
a.id="parent"===e?b:"partial"===h?c:b;a.mType=e;G();a=H(e,a);e=!1;(h=d.state("pwState"))&&(e=h.isTryState);e&&(g.isTryState=e);g.triggerEvent=f.twisterFeatureName;a=f.twisterRefreshHandler.createCustomParamsMap(a,g);k.asin=b;k.id=c;return{twisterRefreshParams:a,notifyClientParams:k}}function G(){var b=[];k.each(["full","parent","partial","master"],function(c,e){k.each(p.contextMetaData[e].mTypeSpecificURLParams,function(c,a){b.push(c)})});f.twisterRefreshHandler.removeParams(b)}function H(b,c){k.each(p.contextMetaData[b].mTypeSpecificURLParams,
function(b,h){c[b]=h});return c}function I(b){b=f.twisterUtil.getSelectionInfoFromSelectedVariationValuesMap(b.selected_variation_values);f.twisterUtil.isFullySelected(b)?f.currentPageSelectionState="full":f.currentPageSelectionState="partial"}function J(b){var c={};c.config=b.measurement;c.dimensionDisplayType=b.dimensionsDisplayType;c.storeID=b.storeID;c.productGroupID=b.productGroupID;c.triggerEvent="Twister";return c}function B(b,c){var e;"partial"===b&&"partial"===c&&(e="partial");"partial"===
b&&"full"===c&&(e="full");"full"===b&&"partial"===c&&(e="parent");"full"===b&&"full"===c&&(e="full");return e}var f=this,K=p.parent_asin,t=q.ue,C="",z=new r("dpTwisterPageRefreshView");this.twisterUtil=u.util;this.twisterFeatureName="Twister";this.currentPageSelectionState;this.twisterRefreshHandler;this.config={partial:{},full:{},parent:{},master:{}};this.hiddenFeatures={intermediateEOS:1,EOS:1};f.viewUtil=new n(u);f.subType;var y=function(b){t&&t.count&&t.count(b,(t.count(b)||0)+1)};(function(){I(p);
F();var b={featureName:f.twisterFeatureName},c=J(p);f.twisterRefreshHandler=new D(b,c,null);u.registerPassive({viewAttribution:"DetailPage",viewName:"WebTwisterRefreshView"},{updateView:function(c,b){var a={};if(c!==l.METADATA){var a={},g;g=void 0;if(b)switch(c){case l.VARIATION_CHANGE:g=b.selected().selInfo;break;case l.VARIATION_PEEK:g=b.peek().selInfo}a.selectionInfo=g;a.dimensionCombination=f.viewUtil.getCurrDimCombId(a.selectionInfo,"_","X");g=f.twisterUtil.isFullySelected(a.dimensionCombination);
a.childAsin=f.twisterUtil.getAsinFromSelectionInfo(a.selectionInfo,g);a.newPageSelectionState=g?"full":"partial";a.mTypeForRefresh=B(f.currentPageSelectionState,a.newPageSelectionState);a.newAsin="parent"===a.mTypeForRefresh?K:a.childAsin;a.doNotAbort="parent"===a.mTypeForRefresh?!0:!1;a.twisterCallListParams=A(a.mTypeForRefresh,a.newAsin,a.childAsin,a.dimensionCombination,a.newPageSelectionState);a.optionsForTwisterRefresh=x(b);a.pageRefreshMeasure={newAsin:a.newAsin,dimensionType:C,dimensionDisplayType:p.dimensionsDisplayType}}switch(c){case l.VARIATION_CHANGE:f.subType!==
l.PRODUCTIZED_VIEW_SUBTYPE&&(w(a.twisterCallListParams,a.optionsForTwisterRefresh,a.pageRefreshMeasure,a.doNotAbort,!0),f.currentPageSelectionState=a.newPageSelectionState,f.subType=void 0);break;case l.VARIATION_PEEK:w(a.twisterCallListParams,a.optionsForTwisterRefresh,a.pageRefreshMeasure,a.doNotAbort,!1);break;case l.METADATA:switch(b.subType){case l.DP_STATE_VIEW_SUBTYPE:C=b.divMetadata.dimDisplayType;break;case l.PRODUCTIZED_VIEW_SUBTYPE:f.subType=b.subType,a.dimensionCombination=b.newDimCombID,
a.childAsin=b.childAsin,a.newAsin=b.newAsin,a.newPageSelectionState=f.twisterUtil.isFullySelected(a.dimensionCombination)?"full":"partial",a.mTypeForRefresh=B(f.currentPageSelectionState,a.newPageSelectionState),a.doNotAbort="parent"===a.mTypeForRefresh?!0:!1,a.twisterCallListParams=A(a.mTypeForRefresh,a.newAsin,a.childAsin,a.dimensionCombination,a.newPageSelectionState),a.optionsForTwisterRefresh=x(b),a.pageRefreshMeasure={newAsin:a.newAsin,dimensionType:b.divMetaData?b.divMetaData.dimDisplayType:
void 0,dimensionDisplayType:p.dimensionsDisplayType},w(a.twisterCallListParams,a.optionsForTwisterRefresh,a.pageRefreshMeasure,a.doNotAbort,!0),f.currentPageSelectionState=a.newPageSelectionState}}}})})()}});"use strict";m.when("A","twister-util","ready").execute(function(d,m){var n=q.ue;if(void 0!==d.state("dimensionKeyList"))for(var l in d.state("dimensionKeyList").dimensionKeys)void 0!==l&&(d.on("a:popover:beforeShow:mobile-twister_"+l,function(k){void 0===d.state("twisterInteractability")&&n&&
"function"===typeof n.count&&n.count("Twister:blankTwisterSecView",(n.count("Twister:blankTwisterSecView")||0)+1)}),d.on("a:popover:beforeHide:mobile-twister_"+l,function(d){if(d&&d.popover){d=d.popover.getContent();var l=0<d.find(".aw-twister-row:first").length;d&&!l&&n&&"function"===typeof n.count&&n.count("blankTwisterSecondaryView",(n.count("blankTwisterSecondaryView")||0)+1)}}))});"use strict";m.when("A").register("twister-bottom-sheet-container",function(d){return{getInstance:function(){return this.sheetViewInstance},
saveInstance:function(m){this.sheetViewInstance=m;d.trigger("dp:sheet:twister:initialized")}}})});